/*
 * Blink Debit (PayNow and AutoPay) Payments API
 *
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.19
 * Contact: sysadmin@blinkpay.co.nz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BlinkDebitApiClient.Client.OpenAPIDateConverter;

namespace BlinkDebitApiClient.Model.V1
{
    /// <summary>
    /// The bank name. Required if not using Blink&#39;s hosted gateway.
    /// </summary>
    /// <value>The bank name. Required if not using Blink&#39;s hosted gateway.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Bank
    {
        /// <summary>
        /// Enum ASB for value: ASB
        /// </summary>
        [EnumMember(Value = "ASB")]
        ASB = 1,

        /// <summary>
        /// Enum ANZ for value: ANZ
        /// </summary>
        [EnumMember(Value = "ANZ")]
        ANZ = 2,

        /// <summary>
        /// Enum BNZ for value: BNZ
        /// </summary>
        [EnumMember(Value = "BNZ")]
        BNZ = 3,

        /// <summary>
        /// Enum Westpac for value: Westpac
        /// </summary>
        [EnumMember(Value = "Westpac")]
        Westpac = 4,

        /// <summary>
        /// Enum KiwiBank for value: KiwiBank
        /// </summary>
        [EnumMember(Value = "KiwiBank")]
        KiwiBank = 5,

        /// <summary>
        /// Enum PNZ for value: PNZ
        /// </summary>
        [EnumMember(Value = "PNZ")]
        PNZ = 6

    }

}
