/*
 * Blink Debit (PayNow and AutoPay) Payments API
 *
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.19
 * Contact: sysadmin@blinkpay.co.nz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BlinkDebitApiClient.Client.OpenAPIDateConverter;

namespace BlinkDebitApiClient.Model.V1
{
    /// <summary>
    /// The available bank features
    /// </summary>
    [DataContract(Name = "bank_metadata_features")]
    public partial class BankMetadataFeatures : IEquatable<BankMetadataFeatures>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BankMetadataFeatures" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BankMetadataFeatures() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BankMetadataFeatures" /> class.
        /// </summary>
        /// <param name="enduringConsent">enduringConsent (required).</param>
        /// <param name="decoupledFlow">decoupledFlow (required).</param>
        public BankMetadataFeatures(BankMetadataFeaturesEnduringConsent enduringConsent = default(BankMetadataFeaturesEnduringConsent), BankMetadataFeaturesDecoupledFlow decoupledFlow = default(BankMetadataFeaturesDecoupledFlow))
        {
            // to ensure "enduringConsent" is required (not null)
            if (enduringConsent == null)
            {
                throw new ArgumentNullException("enduringConsent is a required property for BankMetadataFeatures and cannot be null");
            }
            this.EnduringConsent = enduringConsent;
            // to ensure "decoupledFlow" is required (not null)
            if (decoupledFlow == null)
            {
                throw new ArgumentNullException("decoupledFlow is a required property for BankMetadataFeatures and cannot be null");
            }
            this.DecoupledFlow = decoupledFlow;
        }

        /// <summary>
        /// Gets or Sets EnduringConsent
        /// </summary>
        [DataMember(Name = "enduring_consent", IsRequired = true, EmitDefaultValue = true)]
        public BankMetadataFeaturesEnduringConsent EnduringConsent { get; set; }

        /// <summary>
        /// Gets or Sets DecoupledFlow
        /// </summary>
        [DataMember(Name = "decoupled_flow", IsRequired = true, EmitDefaultValue = true)]
        public BankMetadataFeaturesDecoupledFlow DecoupledFlow { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BankMetadataFeatures {\n");
            sb.Append("  EnduringConsent: ").Append(EnduringConsent).Append("\n");
            sb.Append("  DecoupledFlow: ").Append(DecoupledFlow).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BankMetadataFeatures);
        }

        /// <summary>
        /// Returns true if BankMetadataFeatures instances are equal
        /// </summary>
        /// <param name="input">Instance of BankMetadataFeatures to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BankMetadataFeatures input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.EnduringConsent == input.EnduringConsent ||
                    (this.EnduringConsent != null &&
                    this.EnduringConsent.Equals(input.EnduringConsent))
                ) && 
                (
                    this.DecoupledFlow == input.DecoupledFlow ||
                    (this.DecoupledFlow != null &&
                    this.DecoupledFlow.Equals(input.DecoupledFlow))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.EnduringConsent != null)
                {
                    hashCode = (hashCode * 59) + this.EnduringConsent.GetHashCode();
                }
                if (this.DecoupledFlow != null)
                {
                    hashCode = (hashCode * 59) + this.DecoupledFlow.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
