/*
 * Blink Debit (PayNow and AutoPay) Payments API
 *
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.19
 * Contact: sysadmin@blinkpay.co.nz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BlinkDebitApiClient.Client.OpenAPIDateConverter;

namespace BlinkDebitApiClient.Model.V1
{
    /// <summary>
    /// The enduring consent bank feature
    /// </summary>
    [DataContract(Name = "bank_metadata_features_enduring_consent")]
    public partial class BankMetadataFeaturesEnduringConsent : IEquatable<BankMetadataFeaturesEnduringConsent>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BankMetadataFeaturesEnduringConsent" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BankMetadataFeaturesEnduringConsent() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BankMetadataFeaturesEnduringConsent" /> class.
        /// </summary>
        /// <param name="enabled">If enduring consent is disabled, only single payment consents can be issued. (required).</param>
        /// <param name="maximumConsent">ISO8601 time duration for the maximum allowed enduring consent period, i.e. how long the consent could be used to execute payments for. Appears only if consent_indefinite is false.</param>
        /// <param name="consentIndefinite">If the consenting period for payments is indefinite or time-limited by the bank.</param>
        public BankMetadataFeaturesEnduringConsent(bool enabled = default(bool), string maximumConsent = default(string), bool consentIndefinite = default(bool))
        {
            this.Enabled = enabled;
            this.MaximumConsent = maximumConsent;
            this.ConsentIndefinite = consentIndefinite;
        }

        /// <summary>
        /// If enduring consent is disabled, only single payment consents can be issued.
        /// </summary>
        /// <value>If enduring consent is disabled, only single payment consents can be issued.</value>
        [DataMember(Name = "enabled", IsRequired = true, EmitDefaultValue = true)]
        public bool Enabled { get; set; }

        /// <summary>
        /// ISO8601 time duration for the maximum allowed enduring consent period, i.e. how long the consent could be used to execute payments for. Appears only if consent_indefinite is false
        /// </summary>
        /// <value>ISO8601 time duration for the maximum allowed enduring consent period, i.e. how long the consent could be used to execute payments for. Appears only if consent_indefinite is false</value>
        /// <example>&quot;P12M0DT00H00M00S&quot;</example>
        [DataMember(Name = "maximum_consent", EmitDefaultValue = false)]
        public string MaximumConsent { get; set; }

        /// <summary>
        /// If the consenting period for payments is indefinite or time-limited by the bank
        /// </summary>
        /// <value>If the consenting period for payments is indefinite or time-limited by the bank</value>
        [DataMember(Name = "consent_indefinite", EmitDefaultValue = true)]
        public bool ConsentIndefinite { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BankMetadataFeaturesEnduringConsent {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  MaximumConsent: ").Append(MaximumConsent).Append("\n");
            sb.Append("  ConsentIndefinite: ").Append(ConsentIndefinite).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BankMetadataFeaturesEnduringConsent);
        }

        /// <summary>
        /// Returns true if BankMetadataFeaturesEnduringConsent instances are equal
        /// </summary>
        /// <param name="input">Instance of BankMetadataFeaturesEnduringConsent to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BankMetadataFeaturesEnduringConsent input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Enabled == input.Enabled ||
                    this.Enabled.Equals(input.Enabled)
                ) && 
                (
                    this.MaximumConsent == input.MaximumConsent ||
                    (this.MaximumConsent != null &&
                    this.MaximumConsent.Equals(input.MaximumConsent))
                ) && 
                (
                    this.ConsentIndefinite == input.ConsentIndefinite ||
                    this.ConsentIndefinite.Equals(input.ConsentIndefinite)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Enabled.GetHashCode();
                if (this.MaximumConsent != null)
                {
                    hashCode = (hashCode * 59) + this.MaximumConsent.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.ConsentIndefinite.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
