/*
 * Blink Debit (PayNow and AutoPay) Payments API
 *
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.19
 * Contact: sysadmin@blinkpay.co.nz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BlinkDebitApiClient.Client.OpenAPIDateConverter;
using System.Reflection;

namespace BlinkDebitApiClient.Model.V1
{
    /// <summary>
    /// The consent details
    /// </summary>
    [JsonConverter(typeof(ConsentDetailJsonConverter))]
    [DataContract(Name = "consent_detail")]
    public partial class ConsentDetail : AbstractOpenAPISchema, IEquatable<ConsentDetail>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConsentDetail" /> class
        /// with the <see cref="EnduringConsentRequest" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of EnduringConsentRequest.</param>
        public ConsentDetail(EnduringConsentRequest actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ConsentDetail" /> class
        /// with the <see cref="SingleConsentRequest" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of SingleConsentRequest.</param>
        public ConsentDetail(SingleConsentRequest actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(EnduringConsentRequest))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(SingleConsentRequest))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: EnduringConsentRequest, SingleConsentRequest");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `EnduringConsentRequest`. If the actual instance is not `EnduringConsentRequest`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of EnduringConsentRequest</returns>
        public EnduringConsentRequest GetEnduringConsentRequest()
        {
            return (EnduringConsentRequest)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `SingleConsentRequest`. If the actual instance is not `SingleConsentRequest`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of SingleConsentRequest</returns>
        public SingleConsentRequest GetSingleConsentRequest()
        {
            return (SingleConsentRequest)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConsentDetail {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, ConsentDetail.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of ConsentDetail
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of ConsentDetail</returns>
        public static ConsentDetail FromJson(string jsonString)
        {
            ConsentDetail newConsentDetail = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newConsentDetail;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(EnduringConsentRequest).GetProperty("AdditionalProperties") == null)
                {
                    newConsentDetail = new ConsentDetail(JsonConvert.DeserializeObject<EnduringConsentRequest>(jsonString, ConsentDetail.SerializerSettings));
                }
                else
                {
                    newConsentDetail = new ConsentDetail(JsonConvert.DeserializeObject<EnduringConsentRequest>(jsonString, ConsentDetail.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("EnduringConsentRequest");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into EnduringConsentRequest: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(SingleConsentRequest).GetProperty("AdditionalProperties") == null)
                {
                    newConsentDetail = new ConsentDetail(JsonConvert.DeserializeObject<SingleConsentRequest>(jsonString, ConsentDetail.SerializerSettings));
                }
                else
                {
                    newConsentDetail = new ConsentDetail(JsonConvert.DeserializeObject<SingleConsentRequest>(jsonString, ConsentDetail.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("SingleConsentRequest");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into SingleConsentRequest: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + matchedTypes);
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newConsentDetail;
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ConsentDetail);
        }

        /// <summary>
        /// Returns true if ConsentDetail instances are equal
        /// </summary>
        /// <param name="input">Instance of ConsentDetail to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConsentDetail input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for ConsentDetail
    /// </summary>
    public class ConsentDetailJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(ConsentDetail).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return ConsentDetail.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
