/*
 * Blink Debit (PayNow and AutoPay) Payments API
 *
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.19
 * Contact: sysadmin@blinkpay.co.nz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BlinkDebitApiClient.Client.OpenAPIDateConverter;

namespace BlinkDebitApiClient.Model.V1
{
    /// <summary>
    /// The decoupled flow hint identifier
    /// </summary>
    [DataContract(Name = "decoupled_flow_hint_allOf")]
    public partial class DecoupledFlowHintAllOf : IEquatable<DecoupledFlowHintAllOf>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets IdentifierType
        /// </summary>
        [DataMember(Name = "identifier_type", IsRequired = true, EmitDefaultValue = true)]
        public IdentifierType IdentifierType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DecoupledFlowHintAllOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DecoupledFlowHintAllOf() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DecoupledFlowHintAllOf" /> class.
        /// </summary>
        /// <param name="identifierType">identifierType (required).</param>
        /// <param name="identifierValue">The identifier value. (required).</param>
        public DecoupledFlowHintAllOf(IdentifierType identifierType = default(IdentifierType), string identifierValue = default(string))
        {
            this.IdentifierType = identifierType;
            // to ensure "identifierValue" is required (not null)
            if (identifierValue == null)
            {
                throw new ArgumentNullException("identifierValue is a required property for DecoupledFlowHintAllOf and cannot be null");
            }
            this.IdentifierValue = identifierValue;
        }

        /// <summary>
        /// The identifier value.
        /// </summary>
        /// <value>The identifier value.</value>
        [DataMember(Name = "identifier_value", IsRequired = true, EmitDefaultValue = true)]
        public string IdentifierValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DecoupledFlowHintAllOf {\n");
            sb.Append("  IdentifierType: ").Append(IdentifierType).Append("\n");
            sb.Append("  IdentifierValue: ").Append(IdentifierValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DecoupledFlowHintAllOf);
        }

        /// <summary>
        /// Returns true if DecoupledFlowHintAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of DecoupledFlowHintAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DecoupledFlowHintAllOf input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.IdentifierType == input.IdentifierType ||
                    this.IdentifierType.Equals(input.IdentifierType)
                ) && 
                (
                    this.IdentifierValue == input.IdentifierValue ||
                    (this.IdentifierValue != null &&
                    this.IdentifierValue.Equals(input.IdentifierValue))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.IdentifierType.GetHashCode();
                if (this.IdentifierValue != null)
                {
                    hashCode = (hashCode * 59) + this.IdentifierValue.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
