/*
 * Blink Debit (PayNow and AutoPay) Payments API
 *
 * APIs to execute Direct Credit payments for customers who use online banking with supported banks.  These APIs power **Blink PayNow** enabling one-off payments, and **Blink AutoPay** enabling recurring payments.  **Request IDs** Request IDs are included in the header in every response, to assist in tracing and debugging.  **API Change Policy** Additive changes may be made to request query parameters and JSON responses. To preserve backward compatibility, endpoint naming updates or JSON elements that already exist will not be removed or renamed until a major version (URL) change. This policy applies only after the official v1 release.
 *
 * The version of the OpenAPI document: 1.0.19
 * Contact: sysadmin@blinkpay.co.nz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BlinkDebitApiClient.Client.OpenAPIDateConverter;

namespace BlinkDebitApiClient.Model.V1
{
    /// <summary>
    /// The value type used to identify the customer with their bank.
    /// </summary>
    /// <value>The value type used to identify the customer with their bank.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum IdentifierType
    {
        /// <summary>
        /// Enum Email for value: email
        /// </summary>
        [EnumMember(Value = "email")]
        Email = 1,

        /// <summary>
        /// Enum PhoneNumber for value: phone_number
        /// </summary>
        [EnumMember(Value = "phone_number")]
        PhoneNumber = 2,

        /// <summary>
        /// Enum MobileNumber for value: mobile_number
        /// </summary>
        [EnumMember(Value = "mobile_number")]
        MobileNumber = 3,

        /// <summary>
        /// Enum BankingUsername for value: banking_username
        /// </summary>
        [EnumMember(Value = "banking_username")]
        BankingUsername = 4,

        /// <summary>
        /// Enum ConsentId for value: consent_id
        /// </summary>
        [EnumMember(Value = "consent_id")]
        ConsentId = 5

    }

}
