using System;
using System.Collections.Generic;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISingleConsentsApi
    {
        /// <summary>
        /// Create Single Consent Create a single payment consent request with the bank that will go to the customer for approval.  A successful response does not indicate a completed consent. The status of the consent can be subsequently checked with the consent ID.
        /// </summary>
        /// <param name="body">The consent request parameters.</param>
        /// <param name="requestId">An optional request ID. If provided, it overrides the interaction ID generated by Blink Debit.</param>
        /// <param name="xCorrelationId">An optional correlation ID for logging chain of events. If provided, it overrides the correlation ID generated by Blink Debit.</param>
        /// <param name="xCustomerIp">The customers IP address</param>
        /// <param name="idempotencyKey">An optional idempotency key to prevent duplicate submissions.</param>
        /// <returns>CreateConsentResponse</returns>
        CreateConsentResponse CreateSingleConsent (SingleConsentRequest body, Guid? requestId, Guid? xCorrelationId, string xCustomerIp, Guid? idempotencyKey);
        /// <summary>
        /// Get Single Consent Get an existing consent by ID.
        /// </summary>
        /// <param name="consentId">The consent ID</param>
        /// <param name="requestId">An optional request ID. If provided, it overrides the interaction ID generated by Blink Debit.</param>
        /// <param name="xCorrelationId">An optional correlation ID for logging chain of events. If provided, it overrides the correlation ID generated by Blink Debit.</param>
        /// <returns>Consent</returns>
        Consent GetSingleConsent (Guid? consentId, Guid? requestId, Guid? xCorrelationId);
        /// <summary>
        /// Revoke Single Consent Revoke an existing consent by ID.
        /// </summary>
        /// <param name="consentId">The consent ID</param>
        /// <param name="requestId">An optional request ID. If provided, it overrides the interaction ID generated by Blink Debit.</param>
        /// <param name="xCorrelationId">An optional correlation ID for logging chain of events. If provided, it overrides the correlation ID generated by Blink Debit.</param>
        /// <returns></returns>
        void RevokeSingleConsent (Guid? consentId, Guid? requestId, Guid? xCorrelationId);
    }
  
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class SingleConsentsApi : ISingleConsentsApi
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SingleConsentsApi"/> class.
        /// </summary>
        /// <param name="apiClient"> an instance of ApiClient (optional)</param>
        /// <returns></returns>
        public SingleConsentsApi(ApiClient apiClient = null)
        {
            if (apiClient == null) // use the default one in Configuration
                this.ApiClient = Configuration.DefaultApiClient; 
            else
                this.ApiClient = apiClient;
        }
    
        /// <summary>
        /// Initializes a new instance of the <see cref="SingleConsentsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SingleConsentsApi(String basePath)
        {
            this.ApiClient = new ApiClient(basePath);
        }
    
        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <param name="basePath">The base path</param>
        /// <value>The base path</value>
        public void SetBasePath(String basePath)
        {
            this.ApiClient.BasePath = basePath;
        }
    
        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <param name="basePath">The base path</param>
        /// <value>The base path</value>
        public String GetBasePath(String basePath)
        {
            return this.ApiClient.BasePath;
        }
    
        /// <summary>
        /// Gets or sets the API client.
        /// </summary>
        /// <value>An instance of the ApiClient</value>
        public ApiClient ApiClient {get; set;}
    
        /// <summary>
        /// Create Single Consent Create a single payment consent request with the bank that will go to the customer for approval.  A successful response does not indicate a completed consent. The status of the consent can be subsequently checked with the consent ID.
        /// </summary>
        /// <param name="body">The consent request parameters.</param>
        /// <param name="requestId">An optional request ID. If provided, it overrides the interaction ID generated by Blink Debit.</param>
        /// <param name="xCorrelationId">An optional correlation ID for logging chain of events. If provided, it overrides the correlation ID generated by Blink Debit.</param>
        /// <param name="xCustomerIp">The customers IP address</param>
        /// <param name="idempotencyKey">An optional idempotency key to prevent duplicate submissions.</param>
        /// <returns>CreateConsentResponse</returns>
        public CreateConsentResponse CreateSingleConsent (SingleConsentRequest body, Guid? requestId, Guid? xCorrelationId, string xCustomerIp, Guid? idempotencyKey)
        {
    
            var path = "/single-consents";
            path = path.Replace("{format}", "json");
                
            var queryParams = new Dictionary<String, String>();
            var headerParams = new Dictionary<String, String>();
            var formParams = new Dictionary<String, String>();
            var fileParams = new Dictionary<String, FileParameter>();
            String postBody = null;
    
                         if (requestId != null) headerParams.Add("request-id", ApiClient.ParameterToString(requestId)); // header parameter
 if (xCorrelationId != null) headerParams.Add("x-correlation-id", ApiClient.ParameterToString(xCorrelationId)); // header parameter
 if (xCustomerIp != null) headerParams.Add("x-customer-ip", ApiClient.ParameterToString(xCustomerIp)); // header parameter
 if (idempotencyKey != null) headerParams.Add("idempotency-key", ApiClient.ParameterToString(idempotencyKey)); // header parameter
            postBody = ApiClient.Serialize(body); // http body (model) parameter

            // authentication setting, if any
            String[] authSettings = new String[] { "Bearer" };
    
            // make the HTTP request
            IRestResponse response = (IRestResponse) ApiClient.CallApi(path, Method.POST, queryParams, postBody, headerParams, formParams, fileParams, authSettings);
    
            if (((int)response.StatusCode) >= 400)
                throw new ApiException ((int)response.StatusCode, "Error calling CreateSingleConsent: " + response.Content, response.Content);
            else if (((int)response.StatusCode) == 0)
                throw new ApiException ((int)response.StatusCode, "Error calling CreateSingleConsent: " + response.ErrorMessage, response.ErrorMessage);
    
            return (CreateConsentResponse) ApiClient.Deserialize(response.Content, typeof(CreateConsentResponse), response.Headers);
        }
    
        /// <summary>
        /// Get Single Consent Get an existing consent by ID.
        /// </summary>
        /// <param name="consentId">The consent ID</param>
        /// <param name="requestId">An optional request ID. If provided, it overrides the interaction ID generated by Blink Debit.</param>
        /// <param name="xCorrelationId">An optional correlation ID for logging chain of events. If provided, it overrides the correlation ID generated by Blink Debit.</param>
        /// <returns>Consent</returns>
        public Consent GetSingleConsent (Guid? consentId, Guid? requestId, Guid? xCorrelationId)
        {
            // verify the required parameter 'consentId' is set
            if (consentId == null) throw new ApiException(400, "Missing required parameter 'consentId' when calling GetSingleConsent");
    
            var path = "/single-consents/{consent_id}";
            path = path.Replace("{format}", "json");
            path = path.Replace("{" + "consent_id" + "}", ApiClient.ParameterToString(consentId));
    
            var queryParams = new Dictionary<String, String>();
            var headerParams = new Dictionary<String, String>();
            var formParams = new Dictionary<String, String>();
            var fileParams = new Dictionary<String, FileParameter>();
            String postBody = null;
    
                         if (requestId != null) headerParams.Add("request-id", ApiClient.ParameterToString(requestId)); // header parameter
 if (xCorrelationId != null) headerParams.Add("x-correlation-id", ApiClient.ParameterToString(xCorrelationId)); // header parameter
            
            // authentication setting, if any
            String[] authSettings = new String[] { "Bearer" };
    
            // make the HTTP request
            IRestResponse response = (IRestResponse) ApiClient.CallApi(path, Method.GET, queryParams, postBody, headerParams, formParams, fileParams, authSettings);
    
            if (((int)response.StatusCode) >= 400)
                throw new ApiException ((int)response.StatusCode, "Error calling GetSingleConsent: " + response.Content, response.Content);
            else if (((int)response.StatusCode) == 0)
                throw new ApiException ((int)response.StatusCode, "Error calling GetSingleConsent: " + response.ErrorMessage, response.ErrorMessage);
    
            return (Consent) ApiClient.Deserialize(response.Content, typeof(Consent), response.Headers);
        }
    
        /// <summary>
        /// Revoke Single Consent Revoke an existing consent by ID.
        /// </summary>
        /// <param name="consentId">The consent ID</param>
        /// <param name="requestId">An optional request ID. If provided, it overrides the interaction ID generated by Blink Debit.</param>
        /// <param name="xCorrelationId">An optional correlation ID for logging chain of events. If provided, it overrides the correlation ID generated by Blink Debit.</param>
        /// <returns></returns>
        public void RevokeSingleConsent (Guid? consentId, Guid? requestId, Guid? xCorrelationId)
        {
            // verify the required parameter 'consentId' is set
            if (consentId == null) throw new ApiException(400, "Missing required parameter 'consentId' when calling RevokeSingleConsent");
    
            var path = "/single-consents/{consent_id}";
            path = path.Replace("{format}", "json");
            path = path.Replace("{" + "consent_id" + "}", ApiClient.ParameterToString(consentId));
    
            var queryParams = new Dictionary<String, String>();
            var headerParams = new Dictionary<String, String>();
            var formParams = new Dictionary<String, String>();
            var fileParams = new Dictionary<String, FileParameter>();
            String postBody = null;
    
                         if (requestId != null) headerParams.Add("request-id", ApiClient.ParameterToString(requestId)); // header parameter
 if (xCorrelationId != null) headerParams.Add("x-correlation-id", ApiClient.ParameterToString(xCorrelationId)); // header parameter
            
            // authentication setting, if any
            String[] authSettings = new String[] { "Bearer" };
    
            // make the HTTP request
            IRestResponse response = (IRestResponse) ApiClient.CallApi(path, Method.DELETE, queryParams, postBody, headerParams, formParams, fileParams, authSettings);
    
            if (((int)response.StatusCode) >= 400)
                throw new ApiException ((int)response.StatusCode, "Error calling RevokeSingleConsent: " + response.Content, response.Content);
            else if (((int)response.StatusCode) == 0)
                throw new ApiException ((int)response.StatusCode, "Error calling RevokeSingleConsent: " + response.ErrorMessage, response.ErrorMessage);
    
            return;
        }
    
    }
}
