name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

  cache:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache NuGet packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

  snyk:
    needs: cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore NuGet packages
        run: dotnet restore
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@0.3.0
        with:
          command: monitor
          args: --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG: blinkpay-zw9
          SNYK_PROJECT_NAME: blink-debit-api-client-dotnet
          WORKING_DIRECTORY: ./src/BlinkDebitApiClient
        continue-on-error: true

  sonar:
    needs: snyk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner
      - name: Restore NuGet packages
        run: dotnet restore
      - name: Run Sonar on blink-debit-api-client-dotnet to inspect code
        run: |
          dotnet sonarscanner begin /k:"blink-debit-api-client-dotnet" /o:"blinkpay" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.branch.name="master"
          dotnet build --configuration Release --no-restore /p:WarningLevel=0
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        continue-on-error: true

  restore_build_test:
    needs: sonar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore /p:WarningLevel=0
      - name: Test
        run: dotnet test --no-restore --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:WarningLevel=0
        env:
          BLINKPAY_CLIENT_ID: ${{ vars.CLIENT_ID }}
          BLINKPAY_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
