name: Deploy

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  nuget_push:
    runs-on: ubuntu-latest
    if: github.event.release.target_commitish == 'master'
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
      - name: Pack
        run: |
          dotnet restore
          dotnet pack --configuration Release /p:PackageVersion=${{ github.event.release.tag_name }}
      - name: Push
        run: 
          dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.NUGET_TOKEN }}
