name: Deploy

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  nuget_push:
    runs-on: ubuntu-latest
    if: github.event.release.target_commitish == 'master'
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          source-url: https://api.nuget.org/v3/index.json
      - name: Pack
        run: |
          dotnet restore
          dotnet pack --configuration Release /p:PackageVersion=${{ github.event.release.tag_name }}
      - name: Push
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_TOKEN }}
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
        run: dotnet nuget push "**/*.nupkg"
